set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)

if(MSVC)
  if(CMAKE_CONFIGURATION_TYPES STREQUAL "Release")
    target_compile_options(${PROJECT_NAME} /O2 /MT)
  elseif(CMAKE_CONFIGURATION_TYPES STREQUAL "Debug")
    target_compile_options(${PROJECT_NAME} /Wall /W4 /Zi)
  endif()
else()
  if(CMAKE_BUILD_TYPE STREQUAL "Release")
    target_compile_options(${PROJECT_NAME} -02)
  elseif(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_options(${PROJECT_NAME} -Wall -Wextra -Werror -g1)
  endif()
endif()